"""empty message

Revision ID: 8b81fcf9c306
Revises: 
Create Date: 2018-02-13 23:36:39.430224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b81fcf9c306'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'AuthImageGallery_ibfk_1', 'AuthImageGallery', type_='foreignkey')
    op.create_foreign_key(None, 'AuthImageGallery', 'persons', ['person_id'], ['person_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'AuthImageGallery', type_='foreignkey')
    op.create_foreign_key(u'AuthImageGallery_ibfk_1', 'AuthImageGallery', 'persons', ['person_id'], ['person_id'])
    # ### end Alembic commands ###
